library(tidyverse)

library(DIALOGUE)

source("../../../Utils/Plotting.R")
source("../../../Utils/utils.R")
source("../../../Utils/colors.R")

# Load Data ---------------------------------------------------------------

dialogue_res = readRDS("../../../Data/Figure 5/CT_5_run_main_out.rds")
all_DE_res = readRDS("../../../Data/Figure 2/updated_sc_DE_markers.rds")

# Link regions to MCPs ----------------------------------------------------
MCP_cell_embed = dialogue_res$full_RA_res$scores %>%
  dplyr::bind_rows() %>%
  rownames_to_column("Cell")
MCP_region_scores = MCP_cell_embed[,c("Cell", paste0("MCP", 1:10),
                                      "Region")] %>%
  gather(key = "MCP", value = "MCP_Score", -Cell, -Region) %>%
  dplyr::group_by(Region, MCP) %>%
  dplyr::summarise(Region_MCP_Score = mean(MCP_Score))

# Compare DE with Dialogue ----------------------------------------

dialogue_sig = MCP_signature_to_df(sig_list = dialogue_res$R$sig2,
                                   min_celltype = 4) %>%
  dplyr::select(-cell_type) %>%
  dplyr::distinct()
region_dialogue_sig_up = dialogue_sig %>%
  dplyr::filter(Direction == "up") %>%
  dplyr::distinct() %>%
  dplyr::left_join(MCP_region_scores) %>%
  dplyr::filter(Region_MCP_Score >= 1)
  # dplyr::select(Region, metabolite) %>%
  # dplyr::distinct()

DE_region_up = all_DE_res$Metabo$Region %>%
  dplyr::filter(avg_log2FC >= 1,
                p_val_adj < 0.05,
                pct.1 >= 0.5) %>%
  dplyr::select(cluster, gene) %>%
  dplyr::distinct() %>%
  `rownames<-`(NULL)
colnames(DE_region_up) = c("Region", "metabolite")

comparison_result <- full_join(DE_region_up,
                               region_dialogue_sig_up,
                               by = c("Region", "metabolite")) %>%
  mutate(Source = case_when(
    paste(Region, metabolite) %in% paste(DE_region_up$Region, DE_region_up$metabolite) &
      paste(Region, metabolite) %in% paste(region_dialogue_sig_up$Region, region_dialogue_sig_up$metabolite) ~ "Both",
    paste(Region, metabolite) %in% paste(DE_region_up$Region, DE_region_up$metabolite) ~ "DE only",
    paste(Region, metabolite) %in% paste(region_dialogue_sig_up$Region, region_dialogue_sig_up$metabolite) ~ "DIALOGUE Only",
    TRUE ~ "Unknown"
  ))


# Export Markers to csv ---------------------------------------------------
# MCP_up_markers_named.csv is now generated by
# Analysis_scripts/Downstream/Generate_Supp_Tables.R from dialogue_res$R$sig2 directly.
