library(DIALOGUE)
library(tidyverse)
library(Seurat)

source("../../../Utils/utils.R")

# Load Data ---------------------------------------------------------------

metabo_RNA_seurat = readRDS("../../../Data/Figure 1/updated_Metabo_RNA_combined_seurat.rds")
spatial_niches = readRDS("../../../Data/Figure 1/spatial_niches_regions.rds")


# Export dialogure input --------------------------------------------------
metabo_RNA_seurat@meta.data$Cell_type_coarse = sub("_.*", "", metabo_RNA_seurat@meta.data$Cell_type_fine)

all_cell_types = unique(metabo_RNA_seurat@meta.data$Cell_type_coarse)
all_cell_types = all_cell_types[!all_cell_types %in% c("Thalamic Neurons",
                                                       "Ventricular systems Glial cells")]
full_rA_updated = list()
for (i in all_cell_types){
  full_rA_updated[[i]] = create_celltype_dialogue(seurat_obj = metabo_RNA_seurat,
                                                  niches_res = spatial_niches,
                                                  cell_type = i)
}

saveRDS(full_rA_updated, "../../../Data/Figure 5/DIALOGUE_input.rds")


# Run DIALOGUE ------------------------------------------------------------
outdir = "../../../Data/Figure 5/updated_DIALOGUE_res"
dir.create(outdir)

param <- DIALOGUE::DLG.get.param(k = 10,
                       results.dir = outdir,
                       conf = c("cellQ"), spatial.flag = T,
                       abn.c = 15,
                       n.genes = 100)
param$averaging.function = colMeans2


D1_res = DIALOGUE:::DIALOGUE1(rA = full_rA_updated,main = "CT_5_run",
                              param = param)
D2_res = DIALOGUE:::DIALOGUE2(rA = full_rA_updated,main = "CT_5_run",
                              results.dir = param$results.dir)

saveRDS(D1_res, "../../../Data/Figure 5/updated_DIALOGUE_res/DIALOGUE1_CT_5_run.rds")
saveRDS(D2_res, "../../../Data/Figure 5/updated_DIALOGUE_res/DIALOGUE2_CT_5_run.rds")

D2_res = readRDS(file.path(outdir, paste0("DIALOGUE2", "_CT_5_run.rds")))
Res = custom_D3_DIALOGUE(rA_list = full_rA_updated, D2_result = D2_res)

saveRDS(Res,
        "../../../Data/Figure 5/CT_5_run_main_out.rds")

# Supp Tables 21 and 22 (MCP scores/loadings, MCP metabolic signatures) are now generated by
# Analysis_scripts/Downstream/Generate_Supp_Tables.R from the saved Res object above.


# Calculate Environment score ---------------------------------------------
Env_scores = calculate_environment_score(ra_res = Res$full_RA_res)

Env_scores$scaled_Es_ij = (Env_scores$Es_ij - min(Env_scores$Es_ij)) /
  (max(Env_scores$Es_ij) - min(Env_scores$Es_ij))

