library(tidyverse)
library(Seurat)
library(ggpubr)


# Load Data ---------------------------------------------------------------

# Collecting eval res -----------------------------------------------------
# Raw per-parameter-combination SpatialGlue eval CSVs from the SLURM sweep
# (SpatialGlue_job_parallel.sh), not checked into Data/. Set to your own cluster storage path.
cluster_base_dir = Sys.getenv("SPATIAL_OMICS_CLUSTER_DIR", "/path/to/your/cluster/storage/Spatial_omics")
root_dir = file.path(cluster_base_dir, "Results/Downstream/SpatialGlue/SpatialGlue_eval")
sg_res_dirs = list.dirs(root_dir, recursive = F, full.names = F)

all_sg_res = list()
for (i in sg_res_dirs){
  x = list.files(file.path(root_dir, i), recursive = F, full.names = F)
  param_combs = list()
  for (j in x){
    param_name = sub(".csv.*", "", j)
    param_data = read.csv(file.path(root_dir, i, j))
    param_combs[[j]] = param_data
  }
  param_combs = param_combs %>% dplyr::bind_rows(.id = "param_comb")
  all_sg_res[[i]] = param_combs
}

saveRDS(all_sg_res, "../../../Data/Figure 6/SG_eval_res_combined.rds")


# Collecting updated eval res ---------------------------------------------
updated_sg_res = list()
for (i in sg_res_dirs){
  file = file.path(root_dir, i, "updated_dim50_k15_metriceuclidean_wf5511.csv")
  if (!file.exists(file)){
    next()
  }
  param_data = read.csv(file)
  updated_sg_res[[i]] = param_data
}

saveRDS(updated_sg_res, "../../../Data/Figure 6/updated_SG_eval_optim_res.rds")

# Plotting metrics res ----------------------------------------------------
all_sg_res = readRDS("../../../Data/Figure 6/SG_eval_res_combined.rds")
metrics_data = all_sg_res$SCIB_metrics %>%
  dplyr::select(-X) %>%
  dplyr::mutate(param_comb = sub(".csv.*", "", param_comb)) %>%
  tidyr::separate(param_comb,
                  into = c("Dim", "K_feat",
                           "metric_feat", "Loss_weights"),
                  sep = "_", remove = F) %>%
  dplyr::mutate(Dim = sub("dim", "", Dim),
                K_feat = sub("k", "", K_feat),
                metric_feat = sub("metric", "", metric_feat),
                Loss_weights = sub("wf", "", Loss_weights)) %>%
  dplyr::mutate(Metric_label = paste0(Metric, ";", Label))

# Supp Table 25 (SpatialGlue param optimization) is now generated by
# Analysis_scripts/Downstream/Generate_Supp_Tables.R from the saved Data/ object above.

tidyheatmaps::tidyheatmap(df = metrics_data,
            rows = param_comb,
            columns = Metric_label,
            values = Value,
            scale = "column",
            annotation_col = c(Label, Metric),
            annotation_row = c(Dim,K_feat, metric_feat, Loss_weights),
            gaps_col = Label,
            gaps_row = Dim,
            show_rownames = F, show_colnames = F,
            border_color = NA,display_numbers = T,
            fontsize_number = 12, cluster_rows = T,
            colors = c("#145afc","#ffffff","#ee4445"),
            cutree_rows = 18,fontsize = 12)


# Deciding on param combs to use ------------------------------------------
scaled_metrics = metrics_data %>%
  dplyr::group_by(Metric_label) %>%
  dplyr::mutate(metric_score = as.numeric(scale(Value))) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(param_comb) %>%
  dplyr::mutate(n_positive_metrics = length(which(metric_score > 0))) %>%
  dplyr::ungroup()

filt_all_pos = scaled_metrics %>%
  dplyr::filter(n_positive_metrics == length(unique(scaled_metrics$Metric_label)))
  # dplyr::select(-Metric, -Metric_label)

filt_avg_labels = filt_all_pos %>%
  dplyr::group_by(param_comb, Metric) %>%
  dplyr::mutate(mean_metric_score = mean(Value)) %>%
  dplyr::select(-Label, -Metric_label, -Value, -metric_score) %>%
  dplyr::distinct() %>%
  dplyr::ungroup()

filt_avg_labels %>%
  ggplot(aes(x = param_comb, y = mean_metric_score, colour = Metric,
             group = Metric)) +
  geom_point(size = 3) +
  geom_line() +
  coord_flip() +
  theme_pubr() +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 14),
        legend.text = element_text(size = 14))

