library(Seurat)
library(tidyverse)
require(sf)
library(ggrepel)
library(ggpubr)
library(pheatmap)
library(fplot)

source("../Utils/utils.R")
source("../Utils/Plotting.R")
source("../Utils/colors.R")
source("../Utils/Figure_analysis.R")

main_plot_outdir = "../../../../Manuscript/Figures/Main/Figure 3"
supp_plot_outdir = "../../../../Manuscript/Figures/Supp/Figure 3"

# Load Data ---------------------------------------------------------------

metabo_RNA_seurat = readRDS("../Data/Figure 1/updated_Metabo_RNA_combined_seurat.rds")
atlas_geojson = readRDS("../Data/Figure 1/updated_atlas_geojson.rds")
DE_res = readRDS("../Data/Figure 2/updated_sc_DE_markers.rds")
brain_ontology = read.csv("../Data/Figure 3/Brain_ontology_df.csv")
all_misty_res = readRDS("../Data/Figure 3/updated_MISTY_metabo_region_result.rds")

ora_res = readRDS("../Data/Figure 3/updated_ORA_regions.rds")
SNR_fisher_res = readRDS("../Data/Figure 3/SNR_region_fisher_res.rds")


# Replace formulas with mol names -----------------------------------------
metabolite_mapping_res = map_metabolite_names(metabo_RNA_seurat)
metabo_RNA_seurat = metabolite_mapping_res$seurat_obj
metabo_molec_mapping = metabolite_mapping_res$mapping

DE_res$Metabo[c("Celltypes", "Metabotype","Region", "CT_Region")] <- lapply(
  DE_res$Metabo[c("Celltypes", "Metabotype","Region", "CT_Region")],
  map_sf_to_names
  )


# Add parent regions ------------------------------------------------------
metabo_RNA_seurat = add_parent_regions(metabo_RNA_seurat)

# Plot DE regions ---------------------------------------------------------
region_metabo_de = filter_de_markers(DE_res$Metabo$Region, directional = TRUE)

p = de_dotplot(metabo_RNA_seurat, region_metabo_de,
               assay = "Metabo", group_by = "region", rotate_x = TRUE)

ggsave(file.path(supp_plot_outdir, "Metabo_region_markers_all.pdf"),
       p, width = 17, height = 11)

# MISTY top X heatmap by region -------------------------------------------

misty_ion_mol_map = metabo_molec_mapping %>%
  dplyr::mutate(ion = gsub("[+-]", "_", ion))
misty_regions_scores = Get_interaction_importance(misty.results = all_misty_res$scenario_3$Regions,
                                                  view = "Metabo",
                                                  cutoff = 2,
                                                  trim.measure = "gain.RMSE",
                                                  trim = 10, clean = T) %>%
  dplyr::left_join(misty_ion_mol_map[, c("ion", "mol_name_one_to_one")], by = c("Predictor" = "ion")) %>%
  dplyr::select(-Predictor) %>%
  dplyr::rename(Predictor = mol_name_one_to_one)
misty_regions_scores <- misty_regions_scores %>%
  mutate(Predictor = tidytext::reorder_within(Predictor, Importance, Target),
         Predictor = sub("__.*", "", Predictor))

top_misty_regions_not_DE = misty_regions_scores %>%
  dplyr::group_by(Target) %>%
  dplyr::slice_max(Importance, n = 2, with_ties = F) %>%
  dplyr::left_join(DE_res$Metabo$Region, by = c("Predictor" = "gene",
                                                "Target" = "cluster")) %>%
  dplyr::filter(!is.na(avg_log2FC)) %>%
  dplyr::filter(between(avg_log2FC, 0, 1))

top_misty_regions_not_DE = reorder_by_hclust(top_misty_regions_not_DE,
                                             row_var = "Predictor",
                                             col_var = "Target",
                                             value_var = "Importance")

p1 = top_misty_regions_not_DE %>%
  ggplot(aes(x = Target, y = Predictor, fill = Importance)) +
  geom_tile(color = "white") +
  geom_text(aes(label = round(Importance, 1)), color = "black") +
  scale_fill_gradient(low = scale_cols$gradient$low,
                      high = scale_cols$gradient$high) +
  theme_pubr() +
  coord_flip() +
  labs(x = "", y = "", fill = "Importance") +
  theme(text = element_text(size = 14)) +
  rotate_x_text(45)

ggsave(file.path(main_plot_outdir, "MISTY_not_DE_top3_Metabo_per_region.pdf"),
       p1, width = 4, height = 7)


# Plot region parent DE dotplot -------------------------------------------
to_remove_metabo = c("prontosil-H")

ft_merge = c("cc" = "fiber tracts",
             "mfbc" = "fiber tracts")
metabo_RNA_seurat@meta.data = metabo_RNA_seurat@meta.data %>%
  dplyr::mutate(region_parent = recode(region_parent, !!! ft_merge))
reg_parent_DE = FindAllMarkers(object = metabo_RNA_seurat,
                               assay = "Metabo",
                               group.by = "region_parent",
                               only.pos = F,
                               logfc.threshold = 0.25,
                               min.cells.group = 20,
                               min.cells.feature = 20,
                               min.pct = 0.1)

# Supp Table 12 (region-parent metabolite markers) is now generated by
# Analysis_scripts/Downstream/Generate_Supp_Tables.R (which re-runs this same FindAllMarkers
# call, since reg_parent_DE isn't persisted anywhere -- see that script's Table 12 section).

region_parent_de = filter_de_markers(reg_parent_DE, lfc_strict = FALSE,
                                     cluster_exclude = "Uncertain",
                                     gene_exclude = to_remove_metabo)

region_parent_agg_long = AverageExpression(metabo_RNA_seurat,
                      assays = "Metabo", group.by = "region_parent",slot = "data")[[1]] %>%
  as.matrix() %>%
  t() %>% scale() %>% t() %>%
  as.data.frame() %>%
  rownames_to_column("gene") %>%
  pivot_longer(-gene, names_to = "region", values_to = "Z_score")

region_parent_de_scored = region_parent_de %>%
  dplyr::left_join(region_parent_agg_long, by = c("gene" = "gene",
                             "cluster" = "region"))

region_parent_de_scored = reorder_by_hclust(region_parent_de_scored,
                                            row_var = "gene",
                                            col_var = "cluster",
                                            value_var = "Z_score")

reg_parent_names = brain_ontology %>%
  dplyr::filter(acronym %in% region_parent_de_scored$cluster) %>%
  dplyr::select(acronym, name) %>%
  dplyr::distinct()

region_parent_de_scored = region_parent_de_scored %>%
  dplyr::left_join(reg_parent_names, by = c("cluster" = "acronym"))

p_dot = ggplot(region_parent_de_scored, aes(x = name, y = gene)) +
  geom_point(aes(size = pct.1, color = Z_score)) +
  scale_color_gradient2(low = scale_cols$div$low,
                        high = scale_cols$div$high,
                        mid = scale_cols$div$mid) +
  scale_size(range = c(1, 4)) +
  theme_pubr(legend = "right") +
  xlab("") + ylab("") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(size = "Percentage\nDetection", color = "Z-Score") +
  theme(text = element_text(size = 16))

ggsave(file.path(main_plot_outdir, "Metabo_region_parent_markers.pdf"),
       p_dot, width = 9, height = 8)

# Spatial cell type confusion region plot --------------------------------------
region_CT_prop = compute_dominant_category_per_region(
  metabo_RNA_seurat@meta.data %>%
    rownames_to_column("Cell") %>%
    dplyr::mutate(cell.type = sub("_.*", "", Cell_type_fine)) %>%
    dplyr::select(Cell, region, cell.type),
  region_col = "region", category_col = "cell.type"
)

CT_region_polygons = prep_atlas_polygons(atlas_geojson, metabo_RNA_seurat, brain_ontology) %>%
  dplyr::left_join(region_CT_prop, by = c("region")) %>%
  dplyr::filter(!is.na(prop))

p1 <- ggplot(CT_region_polygons, aes(fill = cell.type)) +
  geom_sf(color = "white") +
  scale_fill_manual(values = my_cols$fine_cell_types) +
  theme_pubr(legend = "right") +
  theme(
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    aspect.ratio = 1
  ) +
  labs(fill = "Dominant Cell type")
p2 <- ggplot(CT_region_polygons) +
  geom_sf(aes(fill = prop), color = "white", size = 0.1) +
  scale_fill_gradient(low = scale_cols$gradient$low,
                      high = scale_cols$gradient$high) +
  theme_pubr() +
  theme(
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    legend.position = "right",
    aspect.ratio = 1
  ) +
  labs(fill = "Dominance strength")

combined_ct_region = ggarrange(plotlist = list(p1,p2))

ggsave(file.path(main_plot_outdir, "Region_spatial_celltypes_props.pdf"),
       combined_ct_region, width = 8, height = 2)


# Spatial Metabotype confusion region plot --------------------------------------
region_metabotype_prop = compute_dominant_category_per_region(
  metabo_RNA_seurat@meta.data %>%
    rownames_to_column("Cell") %>%
    dplyr::select(Cell, region, Metabotype),
  region_col = "region", category_col = "Metabotype"
)

Metabotype_region_polygons = prep_atlas_polygons(atlas_geojson, metabo_RNA_seurat, brain_ontology) %>%
  dplyr::left_join(region_metabotype_prop, by = c("region" = "region")) %>%
  dplyr::filter(!is.na(prop))


p1 <- ggplot(Metabotype_region_polygons, aes(fill = Metabotype)) +
  geom_sf(color = "white") +
  scale_fill_manual(values = my_cols$metabotypes) +
  scale_alpha(range = c(0.3, 1), guide = "legend") +
  theme_pubr(legend = "right") +
  theme(
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    aspect.ratio = 1
  ) +
  labs(fill = "Dominant Metabotype",
       alpha = "Dominance strength")
p2 <- ggplot(Metabotype_region_polygons) +
  geom_sf(aes(fill = prop), color = "white", size = 0.1) +
  scale_fill_gradient(low = scale_cols$gradient$low,
                      high = scale_cols$gradient$high) +
  theme_pubr() +
  theme(
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    legend.position = "right",
    aspect.ratio = 1
  ) +
  labs(fill = "Dominance strength")

combined_metabotype_region = ggarrange(plotlist = list(p1,p2))

ggsave(file.path(main_plot_outdir, "Region_spatial_metabotypes_props.pdf"),
       combined_metabotype_region, width = 8, height = 3)


# Calculate and plot adjusted mutual information celltype and metabotype to region --------
ami_res = compute_ami_by_region(metabo_RNA_seurat, include_sg = FALSE)
p = plot_ami_barplot(ami_res$plot_data)

ggsave(file.path(main_plot_outdir, "AMI_metabotypes_vs_celltype_region.pdf"),
       p, width = 4, height = 4)

#I also tried clevr::v_measure and I got similar results. So I'll stick with AMI


# ORA subclass enrichment plot --------------------------------------------
p = S2IsoMEr::dotplot_ORA(ORA_res = ora_res)+
  scale_color_gradient(low = scale_cols$gradient$low,
                       high = scale_cols$gradient$high) +
  ggpubr::theme_pubr(legend = "right") +
  ggpubr::rotate_x_text(90) +
  xlab("") +
  theme(text = element_text(size = 14))

ggsave(file.path(main_plot_outdir, "ORA_subclass_region_DE_dotplot.pdf"),
       p, width = 9, height = 6)

# plots comparing MISTY and DE for one region -----------------------------------------------------------------
ion_adduct_mapping = data.frame(ion = metabo_molec_mapping$ion,
                                ion_no_adduct = sub("[+-]", "_", metabo_molec_mapping$ion)) %>%
  dplyr::left_join(metabo_molec_mapping) %>%
  dplyr::rename("ion_sf" = "ion",
                "ion" = "mol_name_one_to_one")

misty_pred_name_mapping = ion_adduct_mapping %>%
  dplyr::select(ion_no_adduct, ion)
colnames(misty_pred_name_mapping) = c("Predictor", "ion")

MISTY_DE_comp = compare_DE_misty(DE_res = DE_res$Metabo$Region,
                                 misty_res = all_misty_res$scenario_3$Regions,
                                 importance_cutoff = 2,
                                 misty_ion_name_mapping = misty_pred_name_mapping) %>%
  dplyr::filter(Cluster == "VL")

sel_cells = rownames(metabo_RNA_seurat@meta.data)[metabo_RNA_seurat$region == "VL"]


de_misty_plots = plot_box_violin_feats(seurat_obj = metabo_RNA_seurat,
                          misty_de_comp = MISTY_DE_comp,
                          subset_cells = sel_cells)

de_misty_plots$mean_variance_plot = de_misty_plots$mean_variance_plot +
  scale_color_manual(values = assign_colors(labels = c("Both","DE only","MISTY Only"), cols = my_cols$de_misty_both))

de_misty_plots$violin_plot = de_misty_plots$violin_plot +
  coord_flip() +
  scale_fill_manual(values = assign_colors(labels = c("Both","DE only","MISTY Only"), cols = my_cols$de_misty_both)) +
  theme(text = element_text(size = 15))

ggsave(file.path(supp_plot_outdir, "Lateral_ventricles_mean_var_plot_DE_MISTY.pdf"),
       de_misty_plots$mean_variance_plot, width = 4, height = 4)

ggsave(file.path(main_plot_outdir, "Lateral_ventricles_boxplot_DE_vs_MISTY.pdf"),
       de_misty_plots$violin_plot, width = 9, height = 5)


# Plot Importance against SNR ---------------------------------------------
p1 = SNR_fisher_res %>%
  dplyr::mutate(Significant = ifelse(fisher_pval_log > -log10(0.05),
                                     "Yes", "No")) %>%
  ggplot(aes(x = FE_score, y = fisher_pval_log, colour = Significant)) +
  geom_point(size = 3) +
  theme_pubr() +
  geom_vline(xintercept = 1, linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  xlab("Fold Enrichment") +
  ylab("-log10(p-value)") +
  scale_color_manual(values = assign_colors(labels = c("Yes", "No"),
                                            cols = my_cols$highlight_colors))

ggsave(file.path(supp_plot_outdir, "MISTY_Importance_SNR_ORA_plot.pdf"),
       p1, width = 4, height = 4)

# Manuscript-text numbers (figure_3_numbers.csv) are generated by
# Fig_scripts/Generate_Figure_Numbers.R.
