library(ComplexHeatmap)
library(tidyverse)
library(mistyR)
library(Seurat)

source("../../../Utils/Plotting.R")
source("../../../Utils/utils.R")
source("../../../Utils/colors.R")

# Load data ---------------------------------------------------------------
metabo_RNA_seurat = readRDS("../../../Data/Figure 1/updated_Metabo_RNA_combined_seurat.rds")


niches_pb_corr = readRDS("../../../Data/Figure 4/Niches_pseudobulk_corr_results.rds")
niches_pb_corr_input = readRDS("../../../Data/Figure 4/Niches_pseudobulk_corr_input.rds")

niches_pb_misty = readRDS("../../../Data/Figure 4/updated_MISTY_Niches_pseudobulk_gene_metabo.rds")

# Compare corr and misty pseudobulk --------------------------------------------------
niches_misty_pb_clean = Get_interaction_importance(misty.results = niches_pb_misty,
                                       view = "gene",
                                       cutoff = 1,
                                       trim.measure = "gain.R2",
                                       trim = 1, clean = T)
ion_adduct_mapping = data.frame(ion = rownames(metabo_RNA_seurat@assays$Metabo),
                                ion_no_adduct = sub("[+-]", "_", rownames(metabo_RNA_seurat@assays$Metabo)))

niches_corr = niches_pb_corr %>%
  # dplyr::filter(abs(coef) >= 0.5) %>%
  dplyr::mutate(feat_A = sub(".*rna_", "", feat_A),
                feat_B = sub(".*metabo_", "", feat_B)) %>%
  dplyr::left_join(ion_adduct_mapping, by = c("feat_B" = "ion")) %>%
  dplyr::select(-feat_B) %>%
  dplyr::rename("feat_B" = "ion_no_adduct")

niches_misty_corr = niches_misty_pb_clean %>%
  dplyr::left_join(niches_corr, by = c("Target" = "feat_B",
                                      "Predictor" = "feat_A")) %>%
  dplyr::filter(!is.na(coef))

misty_only_interesting = niches_misty_corr %>%
  dplyr::group_by(Target) %>%
  dplyr::slice_max(Importance, n = 3, with_ties = T) %>%
  dplyr::filter(between(coef, 0, 0.299),
                between(pearson_coef, 0, 0.299),
                Importance >= 2) %>%
  dplyr::ungroup()

# Supp Table 20 (MISTY vs correlation) is now generated by
# Analysis_scripts/Downstream/Generate_Supp_Tables.R, replicating this join/filter chain
# against the saved Data/ objects directly.

misty_pairs_spatial_plots = list()
for (i in 1:nrow(misty_only_interesting)){
  gene = misty_only_interesting$Predictor[i]
  metabo = ion_adduct_mapping$ion[ion_adduct_mapping$ion_no_adduct == misty_only_interesting$Target[i]]
  p1 <- SpatialFeaturePlot(metabo_RNA_seurat, features = gene) +
    scale_fill_gradient2(low = scale_cols$gradient$low,
                         high = scale_cols$gradient$high)
  p2 <- SpatialFeaturePlot(metabo_RNA_seurat, features = metabo)+
    scale_fill_gradient2(low = scale_cols$gradient_limit$low,
                         high = scale_cols$gradient_limit$high)

  misty_pairs_spatial_plots[[paste0(gene, ";", metabo)]] = p1 + p2

}
niches_pb_corr_input_df = as.data.frame(niches_pb_corr_input)

misty_pairs_scatter_plots = list()
for (i in names(misty_pairs_spatial_plots)){
  feats = strsplit(i, ";") %>% unlist()
  example = niches_pb_corr_input_df[,c(paste0("rna_", feats[1]),
                     paste0("metabo_", feats[2]))]
  colnames(example) = c("RNA", "Metabo")
  p = example %>%
    ggplot(aes(x = RNA, y = Metabo)) +
    geom_point(size = 2) +
    geom_smooth(method = "lm", se = TRUE, color = "blue") +
    xlab(feats[1]) +
    ylab(feats[2]) +
    theme_pubclean()
  misty_pairs_scatter_plots[[i]] = p
}

p1 = misty_pairs_spatial_plots$`Hk1;C4H9N3O2-H`
p2 = misty_pairs_scatter_plots$`Hk1;C4H9N3O2-H`

export_plot(plot = p1,
            path = file.path("../../../../../../Manuscript/Figures/Main/Figure 4", "MISTY_not_corr_example_spatial.pdf"),
            sideways = T)
export_plot(plot = p2,
            path = file.path("../../../../../../Manuscript/Figures/Main/Figure 4", "MISTY_not_corr_example_scatter.pdf"),
            sideways = T)
