library(tidyverse)
library(ggh4x)

source("../../../Utils/Plotting.R")
source("../../../Utils/utils.R")


# Load data ---------------------------------------------------------------

all_misty_res = readRDS("../../../Data/Figure 3/updated_MISTY_metabo_region_result.rds")
DE_res = readRDS("../../../Data/Figure 2/updated_sc_DE_markers.rds")
metabo_RNA_seurat = readRDS("../../../Data/Figure 1/updated_Metabo_RNA_combined_seurat.rds")

# Replace formulas with mol names -----------------------------------------
metabo_molec_mapping = read.csv("../../../Data/General/updated_annots_w_1_1_mapping.csv")
metabo_molec_mapping$adduct = str_extract(metabo_molec_mapping$ion,
                                          "(\\+|\\-).*")
metabo_molec_mapping$mol_name_one_to_one = paste0(metabo_molec_mapping$mol_name_one_to_one, metabo_molec_mapping$adduct)

rownames(metabo_RNA_seurat@assays$Metabo) = metabo_molec_mapping$mol_name_one_to_one[
  metabo_molec_mapping$ion == rownames(metabo_RNA_seurat@assays$Metabo)]




# Supp Table 15 (MISTY region-predictive metabolites) is now generated by
# Analysis_scripts/Downstream/Generate_Supp_Tables.R from all_misty_res directly.

# Calculate Importance SNR ------------------------------------------------
ion_adduct_mapping = data.frame(ion = metabo_molec_mapping$ion,
                                ion_no_adduct = sub("[+-]", "_", metabo_molec_mapping$ion)) %>%
  dplyr::left_join(metabo_molec_mapping) %>%
  dplyr::rename("ion_sf" = "ion",
                "ion" = "mol_name_one_to_one")
misty_pred_name_mapping = ion_adduct_mapping %>%
  dplyr::select(ion_no_adduct, ion)
colnames(misty_pred_name_mapping) = c("Predictor", "ion")

snr_per_region_df = SNR_per_region(seurat_obj = metabo_RNA_seurat, region = "VL")
Misty_col_names = c(Metabolite = "Predictor", Cluster = "Target",
                    Score = "Importance")

fisher_res_all = list()
all_regs = intersect(snr_per_region_df$group,
                     unique(all_misty_res$scenario_3$Regions$importances$Target))
all_regs = all_regs[all_regs!="Uncertain"]
for (i in all_regs){
  region_snr_data = snr_per_region_df %>% dplyr::filter(group == i)

  misty_imp_VL = all_misty_res$scenario_3$Regions$importances %>%
    dplyr::left_join(misty_pred_name_mapping, by = "Predictor") %>%
    dplyr::select(-Predictor) %>%
    dplyr::rename("Predictor" = "ion") %>%
    dplyr::select(Predictor, Target, Importance) %>%
    dplyr::rename(all_of(Misty_col_names)) %>%
    dplyr::filter(Cluster == gsub("-", "_", i))

  region_snr_data = region_snr_data %>%
    dplyr::left_join(misty_imp_VL, by = c("feature" = "Metabolite"))
  fisher_res_all[[i]] = Run_fisher_SNR_importance(reg_data = region_snr_data)
}

fisher_res_all = fisher_res_all %>% dplyr::bind_rows()
saveRDS(fisher_res_all, "../../../Data/Figure 3/SNR_region_fisher_res.rds")

# Supp Table 16 (MISTY SNR enrichment) is now generated by
# Analysis_scripts/Downstream/Generate_Supp_Tables.R from this saved Data/ object.
