library(tidyverse)
library(mistyR)
library(Seurat)

source("../../../Utils/utils.R")


# Load data ---------------------------------------------------------------

metabo_RNA_seurat = readRDS("../../../Data/Figure 1/updated_Metabo_RNA_combined_seurat.rds")
#spatial_niches = readRDS("../../../Data/Figure 1/spatial_niches_regions.rds")

# Prepare data for gene-metabo prediction across niches ---------------------------------
pseudo_bulk_niches = metabo_RNA_seurat
pseudo_bulk_niches@graphs = list()
pseudo_bulk_niches = AggregateExpression(object = pseudo_bulk_niches,
                                   assays = c("Metabo","RNA"), return.seurat = T,
                                   group.by = "Niche")

niches_metabo = as.matrix(GetAssayData(pseudo_bulk_niches,
                                      layer = "data",
                                      assay = "Metabo")) %>%
  t() %>%
  as.data.frame()
colnames(niches_metabo) = sub("[+-]", "_", colnames(niches_metabo))
niches_RNA = as.matrix(GetAssayData(pseudo_bulk_niches,
                                   layer = "data",
                                   assay = "RNA")) %>%
  t() %>% as.data.frame()

# Run MISTY gene-metabo prediction across niches --------------------------
# Raw per-run mistyR output, regenerated fresh each run -- lands in Data/ like other
# per-region MISTY output (see Data/Figure 3/updated_MISTY_metabo_regions/)
with_intra_dir = "../../../Data/Figure 4/updated_with_intra"
without_intra_dir = "../../../Data/Figure 4/updated_without_intra"


metabo_expr_view = create_initial_view(niches_metabo)
comp_view = create_view("Gene_expr",
                        niches_RNA,
                        "gene")

combined_views = metabo_expr_view %>%
  add_views(comp_view)

run_misty(views = combined_views,results.folder = with_intra_dir,
          bypass.intra = F)
run_misty(views = combined_views,results.folder = without_intra_dir,
          bypass.intra = T)

with_intra_misty_res = collect_results(with_intra_dir)
without_intra_misty_res = collect_results(without_intra_dir)

misty_res = with_intra_misty_res

saveRDS(misty_res,"../../../Data/Figure 4/updated_MISTY_Niches_pseudobulk_gene_metabo.rds")

# Supp Table 19 (MISTY gene contribution) is now generated by
# Analysis_scripts/Downstream/Generate_Supp_Tables.R from this saved Data/ object.

misty_res %>%
  plot_improvement_stats("intra.R2")%>%
  plot_improvement_stats("gain.R2")

misty_res %>%
  plot_improvement_stats("gain.R2", trim = 1)

p = misty_res %>%
  plot_interaction_heatmap("gene", clean = TRUE,
                           trim.measure = "gain.R2",cutoff = 1.5,
                           trim = 1)


# Plot pred accuracy RMSE -------------------------------------------------
with_intra_RMSE = with_intra_misty_res$improvements %>%
  dplyr::filter(measure %in% c("gain.RMSE", "intra.RMSE",
                               "multi.RMSE", "p.RMSE")) %>%
  dplyr::mutate(measure = paste0("intra", "_", measure)) %>%
  spread(key = "measure", value = "value")

without_intra_RMSE = without_intra_misty_res$improvements %>%
  dplyr::filter(measure %in% c("gain.RMSE", "intra.RMSE",
                               "multi.RMSE", "p.RMSE")) %>%
  dplyr::mutate(measure = paste0("no.intra", "_", measure)) %>%
  spread(key = "measure", value = "value")

rmse_comparison = cbind.data.frame(with_intra_RMSE, without_intra_RMSE) %>%
  dplyr::select(-target, -sample)


p1 = rmse_comparison %>%
  ggplot(aes(x = intra_multi.RMSE, y = no.intra_multi.RMSE)) +
  geom_point(size = 2) +
  geom_abline() +
  theme_pubr()

p2 = rmse_comparison %>%
  ggplot(aes(x = intra_intra.RMSE, y = no.intra_intra.RMSE)) +
  geom_point(size = 2) +
  geom_abline() +
  theme_pubr()

p3 = rmse_comparison %>%
  ggplot(aes(x = intra_gain.RMSE, y = no.intra_gain.RMSE,
             colour = intra_gain.RMSE > 1)) +
  geom_point(size = 3) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 1) +
  scale_color_manual(values = c("FALSE" = "black", "TRUE" = "salmon")) +
  theme_pubr()


p4 = with_intra_misty_res %>% plot_view_contributions(trim.measure = "gain.RMSE",
                                                      trim = 1)

ggarrange(p2, p1, p3, p4, labels = c("A", "B", "C", "D"))


